# Source: EdgeX/templates/edgex-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
# Source: EdgeX/templates/edgex-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-etc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Mi
---
# Source: EdgeX/templates/edgex-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-log
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
# Source: EdgeX/templates/edgex-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuiper-plugins
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
