apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-no-secty.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: core-keeper
  name: core-keeper
spec:
  ports:
    - name: "59890"
      port: 59890
      targetPort: 59890
  selector:
    io.kompose.service: core-keeper
