apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: secret-store-config
  name: secret-store-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
