apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: security-proxy-auth
  name: security-proxy-auth
spec:
  ports:
    - name: "59842"
      port: 59842
      targetPort: 59842
  selector:
    io.kompose.service: security-proxy-auth
