apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-sec.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: security-proxy-setup
  name: security-proxy-setup
spec:
  ports:
    - name: "54325"
      port: 54325
      targetPort: 54325
  selector:
    io.kompose.service: security-proxy-setup
