apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: security-secretstore
  name: security-secretstore
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
