apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-no-secty.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: core-data
  name: core-data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: core-data
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-no-secty.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: core-data
    spec:
      containers:
        - args:
            - --registry
            - -cp=keeper.http://core-keeper:59890
          env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: SERVICE_HOST
              value: edgex-core-data
          image: domain:5000/edgex/core-data:4.0.0
          name: core-data
          ports:
            - containerPort: 59880
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: core-data-cm0
              readOnly: true
              subPath: localtime
      hostname: edgex-core-data
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: core-data-cm0
          name: core-data-cm0
