apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mqtt-broker
  name: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt-broker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: mqtt-broker
    spec:
      containers:
        - args:
            - /usr/sbin/mosquitto
            - -c
            - /mosquitto-no-auth.conf
          image: domain:5000/eclipse-mosquitto:2.0.21
          name: mqtt-broker
          ports:
            - containerPort: 1883
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 2001
            runAsUser: 2002
      hostname: mqtt-broker
      restartPolicy: Always
