apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rules-engine-claim8
  name: rules-engine-claim8
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
