apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: secret-store-logs
  name: secret-store-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
