apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: secret-store-file
  name: secret-store-file
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
