apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-zero-trust.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: security-secretstore-setup
  name: security-secretstore-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: security-secretstore-setup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-zero-trust.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: security-secretstore-setup
    spec:
      containers:
        - env:
            - name: CLIENTS_SECURITY_SECRETSTORE_SETUP_HOST
              value: edgex-security-secretstore-setup
            - name: EDGEX_ADD_KNOWN_SECRETS
              value: postgres[app-rules-engine],message-bus[app-rules-engine],message-bus[device-rest],message-bus[device-virtual]
            - name: EDGEX_ADD_SECRETSTORE_TOKENS
            - name: EDGEX_GROUP
              value: "2001"
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "true"
            - name: EDGEX_USER
              value: "2002"
            - name: PROXY_SETUP_HOST
              value: edgex-security-proxy-setup
            - name: SECRETSTORE_HOST
              value: edgex-secret-store
            - name: SECUREMESSAGEBUS_TYPE
              value: mqtt
            - name: SERVICE_HOST
              value: edgex-security-secretstore-setup
            - name: STAGEGATE_BOOTSTRAPPER_HOST
              value: edgex-security-bootstrapper
            - name: STAGEGATE_BOOTSTRAPPER_STARTPORT
              value: "54321"
            - name: STAGEGATE_DATABASE_HOST
              value: edgex-postgres
            - name: STAGEGATE_DATABASE_PORT
              value: "5432"
            - name: STAGEGATE_DATABASE_READYPORT
              value: "5432"
            - name: STAGEGATE_PROXYSETUP_READYPORT
              value: "54325"
            - name: STAGEGATE_READY_TORUNPORT
              value: "54329"
            - name: STAGEGATE_REGISTRY_HOST
              value: edgex-core-keeper
            - name: STAGEGATE_REGISTRY_PORT
              value: "59890"
            - name: STAGEGATE_REGISTRY_READYPORT
              value: "54324"
            - name: STAGEGATE_SECRETSTORESETUP_HOST
              value: edgex-security-secretstore-setup
            - name: STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT
              value: "54322"
            - name: STAGEGATE_WAITFOR_TIMEOUT
              value: 60s
          image: edgexfoundry/security-secretstore-setup:4.0.0
          name: edgex-security-secretstore-setup
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: security-secretstore-setup-cm0
              readOnly: true
              subPath: localtime
            - mountPath: /edgex-init
              name: edgex-init
              readOnly: true
            - mountPath: /openbao/config
              name: secret-store-config
            - mountPath: /tmp/edgex/secrets
              name: security-secretstore-setup-claim3
            - mountPath: /tmp/kuiper
              name: kuiper-sources
            - mountPath: /tmp/kuiper-connections
              name: kuiper-connections
            - mountPath: /run
              name: security-secretstore-setup-tmpfs0
            - mountPath: /openbao
              name: security-secretstore-setup-tmpfs1
      hostname: edgex-security-secretstore-setup
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: security-secretstore-setup-cm0
          name: security-secretstore-setup-cm0
        - name: edgex-init
          persistentVolumeClaim:
            claimName: edgex-init
            readOnly: true
        - name: secret-store-config
          persistentVolumeClaim:
            claimName: secret-store-config
        - name: security-secretstore-setup-claim3
          persistentVolumeClaim:
            claimName: security-secretstore-setup-claim3
        - name: kuiper-sources
          persistentVolumeClaim:
            claimName: kuiper-sources
        - name: kuiper-connections
          persistentVolumeClaim:
            claimName: kuiper-connections
        - emptyDir:
            medium: Memory
          name: security-secretstore-setup-tmpfs0
        - emptyDir:
            medium: Memory
          name: security-secretstore-setup-tmpfs1
