apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: support-scheduler-claim2
  name: support-scheduler-claim2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
