apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: edgex-init
  name: edgex-init
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
