apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: security-secretstore-setup-claim3
  name: security-secretstore-setup-claim3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
