apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: core-metadata
  name: core-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: core-metadata
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: core-metadata
    spec:
      containers:
        - args:
            - --registry
            - -cp=keeper.http://core-keeper:59890
          env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: SERVICE_HOST
              value: core-metadata
          image: domain:5000/edgexfoundry/core-metadata:4.0.0
          name: core-metadata
          ports:
            - containerPort: 59881
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: core-metadata-cm0
              readOnly: true
              subPath: localtime
      hostname: core-metadata
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: core-metadata-cm0
          name: core-metadata-cm0
