apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: rules-engine
  name: rules-engine
spec:
  ports:
    - name: "59720"
      port: 59720
      targetPort: 59720
  selector:
    io.kompose.service: rules-engine
