apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  type: LoadBalancer
  selector:
    io.kompose.service: ui
