apiVersion: v1
binaryData:
  localtime: VkZwcFpqSUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFkQUFBQUF3QUFBQXlBQUFBQW9KZWlnS0Y1QlBESVdWNkF5UW41Y01uVHZRRExCWXJ3eTN4QUFOSTdQdkRUaTN1QTFFS3Q4TlZGSWdEV1RML3cxenkvQU5nR1puRFpIZktBMlVGODhCNjZVaUFmYVp1UUlINkVvQ0ZKZlpBaVo2RWdJeWxma0NSSGd5QWxFbndRSmlkbElDYnlYaEFvQjBjZ0tOSkFFQUlCQWdFQ0FRSUJBZ0VDQVFJQkFnRUNBUUlCQWdFQ0FRSUJBZ0VDQUFCeDF3QUFBQUIra0FFRUFBQndnQUFJVEUxVUFFTkVWQUJEVTFRQVZGcHBaaklBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBZEFBQUFBd0FBQUF6Ly8vLy9malpES2YvLy8vK2dsNktBLy8vLy82RjVCUEQvLy8vL3lGbGVnUC8vLy8vSkNmbHcvLy8vLzhuVHZRRC8vLy8veXdXSzhQLy8vLy9MZkVBQS8vLy8vOUk3UHZELy8vLy8wNHQ3Z1AvLy8vL1VRcTN3Ly8vLy85VkZJZ0QvLy8vLzFreS84UC8vLy8vWFBMOEEvLy8vLzlnR1puRC8vLy8vMlIzeWdQLy8vLy9aUVh6d0FBQUFBQjY2VWlBQUFBQUFIMm1ia0FBQUFBQWdmb1NnQUFBQUFDRkpmWkFBQUFBQUltZWhJQUFBQUFBaktWK1FBQUFBQUNSSGd5QUFBQUFBSlJKOEVBQUFBQUFtSjJVZ0FBQUFBQ2J5WGhBQUFBQUFLQWRISUFBQUFBQW8wa0FRQWdFQ0FRSUJBZ0VDQVFJQkFnRUNBUUlCQWdFQ0FRSUJBZ0VDQVFJQUFISFhBQUFBQUg2UUFRUUFBSENBQUFoTVRWUUFRMFJVQUVOVFZBQUtRMU5VTFRnSw==
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: database
  name: database-cm0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-data
  name: db-data
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: edgex_db
            - name: POSTGRES_PASSWORD
              value: postgres
          image: domain:5000/postgres:17.5-alpine3.21
          name: database
          ports:
            - containerPort: 5432
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: database-cm0
              readOnly: true
              subPath: localtime
            - mountPath: /var/lib/postgresql/data
              name: db-data
              subPath: postgres-data
            - mountPath: /run
              name: database-tmpfs0
      hostname: database
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: database-cm0
          name: database-cm0
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
        - emptyDir:
            medium: Memory
          name: database-tmpfs0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: database
