apiVersion: v1
binaryData:
  localtime: VkZwcFpqSUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFkQUFBQUF3QUFBQXlBQUFBQW9KZWlnS0Y1QlBESVdWNkF5UW41Y01uVHZRRExCWXJ3eTN4QUFOSTdQdkRUaTN1QTFFS3Q4TlZGSWdEV1RML3cxenkvQU5nR1puRFpIZktBMlVGODhCNjZVaUFmYVp1UUlINkVvQ0ZKZlpBaVo2RWdJeWxma0NSSGd5QWxFbndRSmlkbElDYnlYaEFvQjBjZ0tOSkFFQUlCQWdFQ0FRSUJBZ0VDQVFJQkFnRUNBUUlCQWdFQ0FRSUJBZ0VDQUFCeDF3QUFBQUIra0FFRUFBQndnQUFJVEUxVUFFTkVWQUJEVTFRQVZGcHBaaklBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBZEFBQUFBd0FBQUF6Ly8vLy9malpES2YvLy8vK2dsNktBLy8vLy82RjVCUEQvLy8vL3lGbGVnUC8vLy8vSkNmbHcvLy8vLzhuVHZRRC8vLy8veXdXSzhQLy8vLy9MZkVBQS8vLy8vOUk3UHZELy8vLy8wNHQ3Z1AvLy8vL1VRcTN3Ly8vLy85VkZJZ0QvLy8vLzFreS84UC8vLy8vWFBMOEEvLy8vLzlnR1puRC8vLy8vMlIzeWdQLy8vLy9aUVh6d0FBQUFBQjY2VWlBQUFBQUFIMm1ia0FBQUFBQWdmb1NnQUFBQUFDRkpmWkFBQUFBQUltZWhJQUFBQUFBaktWK1FBQUFBQUNSSGd5QUFBQUFBSlJKOEVBQUFBQUFtSjJVZ0FBQUFBQ2J5WGhBQUFBQUFLQWRISUFBQUFBQW8wa0FRQWdFQ0FRSUJBZ0VDQVFJQkFnRUNBUUlCQWdFQ0FRSUJBZ0VDQVFJQUFISFhBQUFBQUg2UUFRUUFBSENBQUFoTVRWUUFRMFJVQUVOVFZBQUtRMU5VTFRnSw==
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: ui
  name: ui-cm0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: SERVICE_HOST
              value: ui
          image: domain:5000/edgex/edgex-ui:4.0.0
          name: ui
          ports:
            - containerPort: 4000
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: false
            #runAsGroup: 2001
            #runAsUser: 2002
          volumeMounts:
            - mountPath: /etc/localtime
              name: ui-cm0
              readOnly: true
              subPath: localtime
      hostname: ui
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: ui-cm0
          name: ui-cm0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-k3s.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  type: LoadBalancer
  selector:
    io.kompose.service: ui
