apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-no-secty.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: core-data
  name: edgex-core-data
spec:
  ports:
    - name: "59880"
      port: 59880
      targetPort: 59880
  selector:
    io.kompose.service: core-data
