apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-no-secty.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-no-secty.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: SERVICE_HOST
              value: edgex-ui-go
          image: domain:5000/edgexfoundry/edgex-ui:4.0.0
          name: edgex-ui-go
          ports:
            - containerPort: 4000
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 2001
            runAsUser: 2002
          volumeMounts:
            - mountPath: /etc/localtime
              name: ui-cm0
              readOnly: true
              subPath: localtime
      hostname: edgex-ui-go
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: ui-cm0
          name: ui-cm0
