apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: app-rules-engine-claim2
  name: app-rules-engine-claim2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
