apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: app-rules-engine
  name: app-rules-engine
spec:
  ports:
    - name: "59701"
      port: 59701
      targetPort: 59701
  selector:
    io.kompose.service: app-rules-engine
