apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: core-data-claim2
  name: core-data-claim2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
