apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: device-virtual-claim2
  name: device-virtual-claim2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
