apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kuiper-plugins
  name: kuiper-plugins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
