apiVersion: v1
binaryData:
  localtime: VkZwcFpqSUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFkQUFBQUF3QUFBQXlBQUFBQW9KZWlnS0Y1QlBESVdWNkF5UW41Y01uVHZRRExCWXJ3eTN4QUFOSTdQdkRUaTN1QTFFS3Q4TlZGSWdEV1RML3cxenkvQU5nR1puRFpIZktBMlVGODhCNjZVaUFmYVp1UUlINkVvQ0ZKZlpBaVo2RWdJeWxma0NSSGd5QWxFbndRSmlkbElDYnlYaEFvQjBjZ0tOSkFFQUlCQWdFQ0FRSUJBZ0VDQVFJQkFnRUNBUUlCQWdFQ0FRSUJBZ0VDQUFCeDF3QUFBQUIra0FFRUFBQndnQUFJVEUxVUFFTkVWQUJEVTFRQVZGcHBaaklBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBZEFBQUFBd0FBQUF6Ly8vLy9malpES2YvLy8vK2dsNktBLy8vLy82RjVCUEQvLy8vL3lGbGVnUC8vLy8vSkNmbHcvLy8vLzhuVHZRRC8vLy8veXdXSzhQLy8vLy9MZkVBQS8vLy8vOUk3UHZELy8vLy8wNHQ3Z1AvLy8vL1VRcTN3Ly8vLy85VkZJZ0QvLy8vLzFreS84UC8vLy8vWFBMOEEvLy8vLzlnR1puRC8vLy8vMlIzeWdQLy8vLy9aUVh6d0FBQUFBQjY2VWlBQUFBQUFIMm1ia0FBQUFBQWdmb1NnQUFBQUFDRkpmWkFBQUFBQUltZWhJQUFBQUFBaktWK1FBQUFBQUNSSGd5QUFBQUFBSlJKOEVBQUFBQUFtSjJVZ0FBQUFBQ2J5WGhBQUFBQUFLQWRISUFBQUFBQW8wa0FRQWdFQ0FRSUJBZ0VDQVFJQkFnRUNBUUlCQWdFQ0FRSUJBZ0VDQVFJQUFISFhBQUFBQUg2UUFRUUFBSENBQUFoTVRWUUFRMFJVQUVOVFZBQUtRMU5VTFRnSw==
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: security-proxy-setup
  name: security-proxy-setup-cm0
