apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: security-proxy-setup-claim5
  name: security-proxy-setup-claim5
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
