apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-no-secty-with-app-sample.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: app-sample
  name: edgex-app-sample
spec:
  ports:
    - name: "59700"
      port: 59700
      targetPort: 59700
  selector:
    io.kompose.service: app-sample
