apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-no-secty.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: support-notifications
  name: edgex-support-notifications
spec:
  ports:
    - name: "59860"
      port: 59860
      targetPort: 59860
  selector:
    io.kompose.service: support-notifications
