apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kuiper-sources
  name: kuiper-sources
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
